language: cpp

before_install:
  - git submodule update --init

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DFMT_EXTRA_TESTS=ON .
  - make -j4
  - make test
