language: cpp

os:
  - linux
  #- osx

env:
  global:
    - secure: |-
        jEPN5RbGT8o+zN8ybGoTzJ1m7gjP/D8vaf5V+A2ZDMayKHXdGMmVtA5FjI9B1aSiq0P4nC
        cbx2lUzQffJJruBqoSI7ZhWaFBNJejVFwOer3MlzxBdNOHOrJwwf1FpgypaheCHyLebQa5
        JIGZrLK2XoLb7s00FybNCZEgEvUT7W4=
  matrix:
    - BUILD=Doc
    #- BUILD=Debug
    #- BUILD=Release

matrix:
  exclude:
    - os: osx
      env: BUILD=Doc

script:
  - support/travis-build.py
