platform:
  - x86
  - x64

install:
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%

before_build: cmake .

build:
  project: FORMAT.sln

test_script:
  - msbuild RUN_TESTS.vcxproj
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test
