environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - BUILD: msvc
    CONFIG: Debug
  - BUILD: msvc
    CONFIG: Release
  - BUILD: mingw
    CONFIG: Debug
  - BUILD: mingw
    CONFIG: Release

install:
  - ps: |
      if ($env:BUILD -eq "mingw") {
        # Install MinGW.
        $url  = "http://sourceforge.net/projects/mingw-w64/files/"
        $url += "Toolchains%20targetting%20Win64/Personal%20BUILDs/"
        $url += "mingw-builds/4.9.2/threads-win32/seh/"
        $url += "x86_64-4.9.2-release-win32-seh-rt_v3-rev1.7z/download"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile mingw.7z
        &7z x -oC:\ mingw.7z > $null
      }
  - set PATH=C:\Program Files (x86)\MSBUILD\12.0\bin\;%PATH%;C:\mingw64\bin

before_build:
  - python support/build.py

build_script:
  - ps: |
      if ($env:BUILD -eq "mingw") {
        mingw32-make -j4
      } else {
        msbuild /m:4 /p:Config=$env:CONFIG FORMAT.sln
      }

test_script:
  - ps: |
      if ($env:BUILD -eq "mingw") {
        mingw32-make test
      } else {
        msbuild RUN_TESTS.vcxproj
      }

on_failure:
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test
