environment:
  matrix:
  - build: msvc
  - build: mingw
    generator: -G "MinGW Makefiles"

configuration:
  - Debug
  - Release

install:
  # Install MinGW.
  - ps: |
      if ($env:build -eq "mingw") {
        $url  = "http://sourceforge.net/projects/mingw-w64/files/"
        $url += "Toolchains%20targetting%20Win64/Personal%20Builds/"
        $url += "mingw-builds/4.9.0/threads-win32/seh/"
        $url += "x86_64-4.9.0-release-win32-seh-rt_v3-rev2.7z/download"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile mingw.7z
        &7z x -oC:\ mingw.7z > $null
      }
  - dir
  - dir C:\
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%;C:\wingw64\bin

before_build:
  - ps: cmake -DFMT_EXTRA_TESTS=ON $env:generator .

build_script:
  - ps: |
      if ($env:build -eq "mingw") {
        mingw32-make -j4
      } else {
        msbuild /m:4 FORMAT.sln
      }

test_script:
  - ps: |
      if ($env:build -eq "mingw") {
        mingw32-make test
      } else {
        msbuild RUN_TESTS.vcxproj
      }

on_failure:
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test
