configuration:
  - Debug
  - Release

install:
  - ps: (wget http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.0/threads-win32/seh/x86_64-4.9.0-release-win32-seh-rt_v3-rev2.7z/download).Content >mingw.7z
  - 7z x -oC:\ mingw.7z
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%;C:\wingw64\bin

before_build: cmake -DFMT_EXTRA_TESTS=ON .

build_script:
  - msbuild /m:4 FORMAT.sln

test_script:
  - msbuild RUN_TESTS.vcxproj

on_failure:
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test
